### ISSUE TITLE
Error Syncing FROM Google

### ISSUE THREAD

**Issue by sjudy** [indictranstech/GCAL#8]
It seems the timezone offset of -4 hours is causing an error.

Traceback (innermost last):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.handler.handle()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 74, in handle
    execute_cmd(cmd)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 99, in execute_cmd
    ret = frappe.call(method, *_frappe.form_dict)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/**init**.py", line 757, in call
    return fn(_args, **newargs)
  File "/home/erpnext/frappe-bench/apps/gcal/gcal/gcal_sync/doctype/sync_configuration/sync_configuration.py", line 102, in sync_calender
    sync_google_calendar(credentials)
  File "/home/erpnext/frappe-bench/apps/gcal/gcal/tasks.py", line 64, in sync_google_calendar
    update_event(e_name, event) if e_name else save_event(event)
  File "/home/erpnext/frappe-bench/apps/gcal/gcal/tasks.py", line 76, in save_event
    e = set_values(e, event)
  File "/home/erpnext/frappe-bench/apps/gcal/gcal/tasks.py", line 95, in set_values
    doc.starts_on = get_formatted_date(start_date)
  File "/home/erpnext/frappe-bench/apps/gcal/gcal/tasks.py", line 223, in get_formatted_date
    date = datetime.strptime(str_date, '%Y-%m-%dT%H:%M:%S').strftime("%Y-%m-%d %H:%M:%S")
  File "/usr/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
 ValueError: unconverted data remains: -04:00

**Comment by gupteshwar** [comment]
Fixed. Please fetch updates.

**Comment by sjudy** [comment]
After a fresh pull, I am still receiving the same error in file "/home/erpnext/frappe-bench/apps/gcal/gcal/tasks.py",

Traceback (innermost last):
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.handler.handle()
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 74, in handle
    execute_cmd(cmd)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/handler.py", line 99, in execute_cmd
    ret = frappe.call(method, *_frappe.form_dict)
  File "/home/erpnext/frappe-bench/apps/frappe/frappe/**init**.py", line 757, in call
    return fn(_args, **newargs)
  File "/home/erpnext/frappe-bench/apps/gcal/gcal/gcal_sync/doctype/sync_configuration/sync_configuration.py", line 102, in sync_calender
    sync_google_calendar(credentials)
  File "/home/erpnext/frappe-bench/apps/gcal/gcal/tasks.py", line 64, in sync_google_calendar
    update_event(e_name, event) if e_name else save_event(event)
  File "/home/erpnext/frappe-bench/apps/gcal/gcal/tasks.py", line 76, in save_event
    e = set_values(e, event)
  File "/home/erpnext/frappe-bench/apps/gcal/gcal/tasks.py", line 95, in set_values
    doc.starts_on = get_formatted_date(start_date)
  File "/home/erpnext/frappe-bench/apps/gcal/gcal/tasks.py", line 223, in get_formatted_date
    date = datetime.strptime(str_date, '%Y-%m-%dT%H:%M:%S').strftime("%Y-%m-%d %H:%M:%S")
  File "/usr/lib/python2.7/_strptime.py", line 328, in _strptime
    data_string[found.end():])
 ValueError: unconverted data remains: -04:00
